import { collection, doc, setDoc, getDocs } from 'firebase/firestore';
import { db } from './firebase';
import { Tenant, Order, StaffDriver } from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-safari-eats',
    name: 'Safari Eats Nairobi',
    slug: 'safari-eats',
    category: 'Food & Gourmet Delivery',
    email: 'orders@safarieats.co.ke',
    phone: '+254712345678',
    currency: 'KES',
    storeLocation: {
      lat: -1.2676,
      lng: 36.8121,
      addressName: 'Sarit Centre, Westlands, Nairobi',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '890123',
      accountType: 'till',
      consumerKey: 'safari_ck_live_928371289371',
      consumerSecret: 'safari_cs_live_1982371982371982',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    orderCount: 142,
    totalRevenue: 345000,
  },
  {
    id: 'tenant-metro-express',
    name: 'Metro Logistics Kenya',
    slug: 'metro-express',
    category: 'Courier & Freight Services',
    email: 'dispatch@metrologistics.co.ke',
    phone: '+254722998877',
    currency: 'KES',
    storeLocation: {
      lat: -1.2864,
      lng: 36.8172,
      addressName: 'Kenyatta Avenue, Nairobi CBD',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '522522',
      accountType: 'paybill',
      consumerKey: 'metro_ck_live_449102930192',
      consumerSecret: 'metro_cs_live_9918239182391823',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    orderCount: 98,
    totalRevenue: 512000,
  },
  {
    id: 'tenant-apex-mombasa',
    name: 'Apex Electronics Mombasa',
    slug: 'apex-mombasa',
    category: 'Consumer Electronics & Gadgets',
    email: 'sales@apexelectronics.co.ke',
    phone: '+254733445566',
    currency: 'KES',
    storeLocation: {
      lat: -4.0435,
      lng: 39.6682,
      addressName: 'City Mall, Nyali, Mombasa',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '400200',
      accountType: 'paybill',
      consumerKey: 'apex_ck_live_112233445566',
      consumerSecret: 'apex_cs_live_665544332211',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    orderCount: 54,
    totalRevenue: 890000,
  },
  {
    id: 'tenant-kisumu-organics',
    name: 'Kisumu Fresh Fish & Organics',
    slug: 'kisumu-organics',
    category: 'Organic Grocery & Fresh Produce',
    email: 'info@kisumufresh.co.ke',
    phone: '+254711223344',
    currency: 'KES',
    storeLocation: {
      lat: -0.1022,
      lng: 34.7617,
      addressName: 'Oginga Odinga Road, Kisumu CBD',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '714900',
      accountType: 'paybill',
      consumerKey: 'kisumu_ck_live_998877665544',
      consumerSecret: 'kisumu_cs_live_112233445566',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    orderCount: 76,
    totalRevenue: 284000,
  },
  {
    id: 'tenant-rift-pharmacy',
    name: 'Rift Valley MediPharma',
    slug: 'rift-pharmacy',
    category: 'Healthcare & Pharmaceuticals',
    email: 'dispatch@riftmedipharma.co.ke',
    phone: '+254720991122',
    currency: 'KES',
    storeLocation: {
      lat: -0.2833,
      lng: 36.0667,
      addressName: 'Kenyatta Avenue, Nakuru Town',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '247247',
      accountType: 'paybill',
      consumerKey: 'rift_ck_live_334455667788',
      consumerSecret: 'rift_cs_live_887766554433',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    orderCount: 62,
    totalRevenue: 410000,
  },
  {
    id: 'tenant-mt-kenya-coffee',
    name: 'Mount Kenya Artisanal Coffee',
    slug: 'mt-kenya-coffee',
    category: 'Specialty Beverage & Roastery',
    email: 'orders@mtkenyacoffee.co.ke',
    phone: '+254700332211',
    currency: 'KES',
    storeLocation: {
      lat: -0.4167,
      lng: 36.9500,
      addressName: 'Nyeri Highway Hub, Nyeri',
      updatedAt: new Date().toISOString(),
    },
    mpesaConfig: {
      paybillOrTill: '888999',
      accountType: 'till',
      consumerKey: 'mtkenya_ck_live_556677889900',
      consumerSecret: 'mtkenya_cs_live_009988776655',
      passkey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
      environment: 'sandbox',
      enabled: true,
    },
    status: 'active',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    orderCount: 38,
    totalRevenue: 195000,
  },
];

export const INITIAL_ORDERS: Record<string, Order[]> = {
  'tenant-safari-eats': [
    {
      id: 'ORD-SE-1001',
      tenantId: 'tenant-safari-eats',
      status: 'out_for_delivery',
      customerId: 'cust-001',
      customerName: 'Amina Mohamed',
      customerPhone: '254712987654',
      deliveryAddress: 'Yaya Towers, Argwings Kodhek Rd, Kilimani',
      destinationLocation: {
        lat: -1.2915,
        lng: 36.7876,
        addressName: 'Kilimani, Nairobi',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -1.2810,
        lng: 36.7980,
        speed: 38,
        heading: 215,
        updatedAt: new Date().toISOString(),
        addressName: 'Ring Road Kilimani',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKH918273X',
        phoneNumber: '254712987654',
        amount: 2850,
        status: 'paid',
        paidAt: new Date(Date.now() - 25 * 60000).toISOString(),
      },
      items: [
        { id: 'item-1', name: 'Swahili Platter (Biryani & Chicken)', quantity: 2, unitPrice: 1100 },
        { id: 'item-2', name: 'Fresh Passion Fruit Juice (1L)', quantity: 1, unitPrice: 450 },
        { id: 'item-3', name: 'Mandazi Bag (6 Pcs)', quantity: 1, unitPrice: 200 },
      ],
      totalAmount: 2850,
      driverId: 'drv-01',
      driverName: 'Juma Omondi',
      driverPhone: '+254720112233',
      estimatedArrivalMinutes: 12,
      timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'ORD-SE-1002',
      tenantId: 'tenant-safari-eats',
      status: 'in_progress',
      customerId: 'cust-002',
      customerName: 'David Njuguna',
      customerPhone: '254722123456',
      deliveryAddress: 'Lavington Mall, James Gichuru Rd',
      destinationLocation: {
        lat: -1.2778,
        lng: 36.7689,
        addressName: 'Lavington, Nairobi',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -1.2676,
        lng: 36.8121,
        speed: 0,
        heading: 0,
        updatedAt: new Date().toISOString(),
        addressName: 'Westlands Kitchen',
      },
      paymentInfo: {
        phoneNumber: '254722123456',
        amount: 1950,
        status: 'unpaid',
      },
      items: [
        { id: 'item-4', name: 'Grilled Nyama Choma & Ugali', quantity: 1, unitPrice: 1650 },
        { id: 'item-5', name: 'Kachumbari Side', quantity: 2, unitPrice: 150 },
      ],
      totalAmount: 1950,
      driverId: 'drv-02',
      driverName: 'Kevin Kiprop',
      driverPhone: '+254721445566',
      estimatedArrivalMinutes: 30,
      timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'ORD-SE-1003',
      tenantId: 'tenant-safari-eats',
      status: 'delivered',
      customerId: 'cust-003',
      customerName: 'Grace Wambui',
      customerPhone: '254733987123',
      deliveryAddress: 'Parklands Avenue, 3rd Parklands',
      destinationLocation: {
        lat: -1.2612,
        lng: 36.8189,
        addressName: 'Parklands, Nairobi',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -1.2612,
        lng: 36.8189,
        speed: 0,
        heading: 0,
        updatedAt: new Date().toISOString(),
        addressName: 'Delivered at Destination',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKG551029P',
        phoneNumber: '254733987123',
        amount: 3400,
        status: 'paid',
        paidAt: new Date(Date.now() - 120 * 60000).toISOString(),
      },
      items: [
        { id: 'item-6', name: 'Family Seafood Fiesta', quantity: 1, unitPrice: 3400 },
      ],
      totalAmount: 3400,
      driverId: 'drv-01',
      driverName: 'Juma Omondi',
      driverPhone: '+254720112233',
      estimatedArrivalMinutes: 0,
      timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
      updatedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    },
  ],
  'tenant-metro-express': [
    {
      id: 'ORD-ME-5001',
      tenantId: 'tenant-metro-express',
      status: 'out_for_delivery',
      customerId: 'cust-101',
      customerName: 'Kenya Commercial Law Ltd',
      customerPhone: '254720554433',
      deliveryAddress: 'Britam Tower, 14th Floor, Upperhill',
      destinationLocation: {
        lat: -1.2995,
        lng: 36.8164,
        addressName: 'Upperhill, Nairobi',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -1.2910,
        lng: 36.8170,
        speed: 42,
        heading: 180,
        updatedAt: new Date().toISOString(),
        addressName: 'Haile Selassie Ave',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKF882341M',
        phoneNumber: '254720554433',
        amount: 4500,
        status: 'paid',
        paidAt: new Date(Date.now() - 10 * 60000).toISOString(),
      },
      items: [
        { id: 'item-m1', name: 'Legal Documents Express Courier', quantity: 1, unitPrice: 4500 },
      ],
      totalAmount: 4500,
      driverId: 'drv-10',
      driverName: 'Samuel Wanyama',
      driverPhone: '+254711889900',
      estimatedArrivalMinutes: 8,
      timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  'tenant-apex-mombasa': [
    {
      id: 'ORD-AP-8001',
      tenantId: 'tenant-apex-mombasa',
      status: 'out_for_delivery',
      customerId: 'cust-201',
      customerName: 'Hassan Ali',
      customerPhone: '254710123987',
      deliveryAddress: 'Links Road, Nyali Beach Estate',
      destinationLocation: {
        lat: -4.0321,
        lng: 39.7012,
        addressName: 'Nyali Beach, Mombasa',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -4.0400,
        lng: 39.6800,
        speed: 50,
        heading: 75,
        updatedAt: new Date().toISOString(),
        addressName: 'Nyali Bridge Link',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKE339012L',
        phoneNumber: '254710123987',
        amount: 68000,
        status: 'paid',
        paidAt: new Date(Date.now() - 50 * 60000).toISOString(),
      },
      items: [
        { id: 'item-a1', name: 'Samsung 55" 4K Smart TV', quantity: 1, unitPrice: 68000 },
      ],
      totalAmount: 68000,
      driverId: 'drv-20',
      driverName: 'Rashid Bakari',
      driverPhone: '+254722331100',
      estimatedArrivalMinutes: 15,
      timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  'tenant-kisumu-organics': [
    {
      id: 'ORD-KO-2001',
      tenantId: 'tenant-kisumu-organics',
      status: 'out_for_delivery',
      customerId: 'cust-301',
      customerName: 'Otieno Odhiambo',
      customerPhone: '254711998877',
      deliveryAddress: 'Milimani Estate, Ring Road Kisumu',
      destinationLocation: {
        lat: -0.1150,
        lng: 34.7550,
        addressName: 'Milimani, Kisumu',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -0.1080,
        lng: 34.7580,
        speed: 40,
        heading: 200,
        updatedAt: new Date().toISOString(),
        addressName: 'Kisumu Port Bypass',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKJ112233K',
        phoneNumber: '254711998877',
        amount: 4800,
        status: 'paid',
        paidAt: new Date(Date.now() - 20 * 60000).toISOString(),
      },
      items: [
        { id: 'item-k1', name: 'Fresh Lake Victoria Tilapia (Whole 3kg)', quantity: 1, unitPrice: 2800 },
        { id: 'item-k2', name: 'Organic Traditional Vegetables (Managu & Sagaa)', quantity: 4, unitPrice: 500 },
      ],
      totalAmount: 4800,
      driverId: 'drv-30',
      driverName: 'Calvince Ochieng',
      driverPhone: '+254711001122',
      estimatedArrivalMinutes: 10,
      timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  'tenant-rift-pharmacy': [
    {
      id: 'ORD-RP-3001',
      tenantId: 'tenant-rift-pharmacy',
      status: 'out_for_delivery',
      customerId: 'cust-401',
      customerName: 'Dr. Elizabeth Chebet',
      customerPhone: '254720123123',
      deliveryAddress: 'Section 58, Nakuru East',
      destinationLocation: {
        lat: -0.2900,
        lng: 36.0800,
        addressName: 'Section 58, Nakuru',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -0.2850,
        lng: 36.0720,
        speed: 45,
        heading: 120,
        updatedAt: new Date().toISOString(),
        addressName: 'Nakuru-Nairobi Highway',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKH445566R',
        phoneNumber: '254720123123',
        amount: 8500,
        status: 'paid',
        paidAt: new Date(Date.now() - 15 * 60000).toISOString(),
      },
      items: [
        { id: 'item-r1', name: 'First Aid Medical Kit & Supplies', quantity: 2, unitPrice: 4250 },
      ],
      totalAmount: 8500,
      driverId: 'drv-40',
      driverName: 'Kiprotich Koech',
      driverPhone: '+254722667788',
      estimatedArrivalMinutes: 7,
      timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  'tenant-mt-kenya-coffee': [
    {
      id: 'ORD-MK-4001',
      tenantId: 'tenant-mt-kenya-coffee',
      status: 'out_for_delivery',
      customerId: 'cust-501',
      customerName: 'James Mwangi',
      customerPhone: '254700987654',
      deliveryAddress: 'Outspan Area, Nyeri',
      destinationLocation: {
        lat: -0.4250,
        lng: 36.9400,
        addressName: 'Outspan, Nyeri',
        updatedAt: new Date().toISOString(),
      },
      currentGpsLocation: {
        lat: -0.4200,
        lng: 36.9450,
        speed: 36,
        heading: 230,
        updatedAt: new Date().toISOString(),
        addressName: 'Nyeri Hill Road',
      },
      paymentInfo: {
        mpesaTransactionId: 'QKG778899M',
        phoneNumber: '254700987654',
        amount: 3200,
        status: 'paid',
        paidAt: new Date(Date.now() - 18 * 60000).toISOString(),
      },
      items: [
        { id: 'item-m1', name: 'Nyeri AA Single Origin Beans (1kg)', quantity: 2, unitPrice: 1600 },
      ],
      totalAmount: 3200,
      driverId: 'drv-50',
      driverName: 'Peter Kamau',
      driverPhone: '+254700112233',
      estimatedArrivalMinutes: 9,
      timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

export const INITIAL_DRIVERS: StaffDriver[] = [
  {
    id: 'drv-01',
    tenantId: 'tenant-safari-eats',
    name: 'Juma Omondi',
    phone: '+254720112233',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -1.2810,
      lng: 36.7980,
      speed: 38,
      heading: 215,
      updatedAt: new Date().toISOString(),
      addressName: 'Ring Road Kilimani',
    },
    activeOrderId: 'ORD-SE-1001',
  },
  {
    id: 'drv-02',
    tenantId: 'tenant-safari-eats',
    name: 'Kevin Kiprop',
    phone: '+254721445566',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -1.2676,
      lng: 36.8121,
      speed: 0,
      heading: 0,
      updatedAt: new Date().toISOString(),
      addressName: 'Sarit Centre Hub',
    },
    activeOrderId: 'ORD-SE-1002',
  },
  {
    id: 'drv-10',
    tenantId: 'tenant-metro-express',
    name: 'Samuel Wanyama',
    phone: '+254711889900',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -1.2910,
      lng: 36.8170,
      speed: 42,
      heading: 180,
      updatedAt: new Date().toISOString(),
      addressName: 'Haile Selassie Ave',
    },
    activeOrderId: 'ORD-ME-5001',
  },
  {
    id: 'drv-20',
    tenantId: 'tenant-apex-mombasa',
    name: 'Rashid Bakari',
    phone: '+254722331100',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -4.0400,
      lng: 39.6800,
      speed: 50,
      heading: 75,
      updatedAt: new Date().toISOString(),
      addressName: 'Nyali Link',
    },
    activeOrderId: 'ORD-AP-8001',
  },
  {
    id: 'drv-30',
    tenantId: 'tenant-kisumu-organics',
    name: 'Calvince Ochieng',
    phone: '+254711001122',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -0.1080,
      lng: 34.7580,
      speed: 40,
      heading: 200,
      updatedAt: new Date().toISOString(),
      addressName: 'Kisumu Port Bypass',
    },
    activeOrderId: 'ORD-KO-2001',
  },
  {
    id: 'drv-40',
    tenantId: 'tenant-rift-pharmacy',
    name: 'Kiprotich Koech',
    phone: '+254722667788',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -0.2850,
      lng: 36.0720,
      speed: 45,
      heading: 120,
      updatedAt: new Date().toISOString(),
      addressName: 'Nakuru-Nairobi Highway',
    },
    activeOrderId: 'ORD-RP-3001',
  },
  {
    id: 'drv-50',
    tenantId: 'tenant-mt-kenya-coffee',
    name: 'Peter Kamau',
    phone: '+254700112233',
    role: 'driver',
    isOnline: true,
    currentGps: {
      lat: -0.4200,
      lng: 36.9450,
      speed: 36,
      heading: 230,
      updatedAt: new Date().toISOString(),
      addressName: 'Nyeri Hill Road',
    },
    activeOrderId: 'ORD-MK-4001',
  },
];

export async function seedDatabaseIfEmpty() {
  try {
    const tenantsSnap = await getDocs(collection(db, 'tenants'));
    const existingIds = new Set(tenantsSnap.docs.map((d) => d.id));

    // Seed any initial tenant that does not exist yet in Firestore
    for (const tenant of INITIAL_TENANTS) {
      if (!existingIds.has(tenant.id)) {
        console.log(`Seeding tenant: ${tenant.name}...`);
        const tenantRef = doc(db, 'tenants', tenant.id);
        await setDoc(tenantRef, tenant);

        // Save orders under tenant -> orderId
        const orders = INITIAL_ORDERS[tenant.id] || [];
        for (const order of orders) {
          const orderRef = doc(db, 'tenants', tenant.id, 'orders', order.id);
          await setDoc(orderRef, order);
        }

        // Save drivers under tenant -> staff
        const drivers = INITIAL_DRIVERS.filter((d) => d.tenantId === tenant.id);
        for (const driver of drivers) {
          const driverRef = doc(db, 'tenants', tenant.id, 'staff', driver.id);
          await setDoc(driverRef, driver);
        }
      }
    }
    return true;
  } catch (error) {
    console.error('Error seeding database:', error);
  }
  return false;
}
